- org.eclipse.richbeans.generator.test/GuiGeneratorRunner.launch
- org.eclipse.richbeans.generator.test/JUnit-org.eclipse.richbeans.generator.test.launch
- org.eclipse.richbeans.generator/src/org/eclipse/richbeans/generator/TwoWayDataBindingProcessor.java
I can't push directly to this repo not sure why?
> Some minor fixes

- org.eclipse.richbeans.releng/build/commit-msg.sh
Signed-off-by: Matthew Gerring <matthew.gerring@gmail.com>
https://github.com/eclipse/richbeans/issues/8
> Updated regex to allow merge

- org.eclipse.richbeans.generator/src/org/eclipse/richbeans/generator/metawidget-metadata.xml
https://github.com/eclipse/richbeans/issues/13
> Update metadata XML file

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesEditingSupport.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> https://github.com/eclipse/richbeans/issues/32

- org.eclipse.richbeans.generator/src/org/eclipse/richbeans/generator/metawidget-metadata.xml
http://jira.diamond.ac.uk/browse/DAQ-47
https://github.com/eclipse/richbeans/issues/13
> Change references to X and Y to Fast and Slow

- org.eclipse.richbeans.repository/pom.xml
https://github.com/eclipse/richbeans/issues/37
> Repository project should have surefire skip tests.

- org.eclipse.richbeans.generator.test/src/org/eclipse/richbeans/generator/test/DialogTest.java
https://github.com/eclipse/richbeans/issues/42
> Improve documentation of DialogTest

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> https://github.com/eclipse/richbeans/issues/53

- .travis.yml
- pom.xml
https://github.com/eclipse/richbeans/issues/46
> Tried to specify tests using variable.

- org.eclipse.richbeans.generator.test/src/org/eclipse/richbeans/generator/test/AllGuiTests.java
Random richbeans issue to satisfy this build system:
https://github.com/eclipse/richbeans/issues/24
> Rename test suite which will apparently fix Dawnsci build

- org.eclipse.richbeans.widgets/.classpath
- org.eclipse.richbeans.widgets/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.richbeans.widgets/META-INF/MANIFEST.MF
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/NumberCellEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/ArrayDecorator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/BoundsDecorator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/FileDecorator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/IDecoratorValidator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/RegexDecorator.java
- pom.xml
https://github.com/eclipse/richbeans/issues/62
> Added delegation to decorators.

- .travis.yml
- org.eclipse.richbeans.generator.test/src/org/eclipse/richbeans/generator/test/Suite.java
- pom.xml
Signed-off-by: Kevin Savage <kevin.savage@diamond.ac.uk>
> Trying using xvfb to run travis gui tests

- org.eclipse.richbeans.generator/src/org/eclipse/richbeans/generator/RichbeansDecoratorWidgetProcessor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/BoundsDecorator.java
https://github.com/eclipse/richbeans/issues/40
> Preserve tooltip when decorating float fields

- org.eclipse.richbeans.generator.test/META-INF/MANIFEST.MF
https://github.com/eclipse/richbeans/issues/72
> junit 4.12 is the minimum

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/FloatDecorator.java
https://github.com/eclipse/richbeans/issues/77
> Added number format

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/BoundsDecorator.java
https://github.com/eclipse/richbeans/issues/77
> Made foreground not black for disabled widgets.

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/BoundsDecorator.java
https://github.com/eclipse/richbeans/issues/77
> Added format and check methods to decorator

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/FileSelectionDialog.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/SelectorWidget.java
https://github.com/eclipse/richbeans/issues/83
> Fix to issue

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/CComboCellEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/BoundsDecorator.java
https://github.com/eclipse/richbeans/issues/87
> Fix to issue 87

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
https://github.com/eclipse/richbeans/issues/89
> More control for SeriesTable

- org.eclipse.richbeans.widgets.file/META-INF/MANIFEST.MF
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesEditingSupport.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesItemContentProposal.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesEventDelegate.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesItemEvent.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesItemListener.java
https://github.com/eclipse/richbeans/issues/91
> Exposed listener for SeriesTable

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
https://github.com/eclipse/richbeans/issues/93
> SeriesTable setSelection(...)

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/ISeriesItemDescriptor.java
https://github.com/eclipse/richbeans/issues/95
> Fix to issue 95

- org.eclipse.richbeans.api/META-INF/MANIFEST.MF
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/event/BoundsEvent.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/generator/IGuiGeneratorService.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/widget/IExpressionWidget.java
https://github.com/eclipse/richbeans/issues/100
> Remove dependency of swt on api bundle.

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/Activator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/Activator.java
They are either found or just black.
> Added block to make icons work better with SWTBot

- org.eclipse.richbeans.widgets.file/.classpath
- org.eclipse.richbeans.widgets.file/.settings/org.eclipse.jdt.core.prefs
- org.eclipse.richbeans.widgets.file/META-INF/MANIFEST.MF
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/FileDialogCellEditor.java
This is tested with an SWTBot test in the scanning project.
> Made invalid files have a red background

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/LongStringCellEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/LongStringDialog.java
> Added long string cell editor which allows value to be edited in place

- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/expression/IRulesEngine.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/expression/IRulesService.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/generator/IGuiGeneratorService.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/generator/IListenableProxyFactory.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/generator/RichbeansAnnotations.java
- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/reflection/RichBeanUtils.java
- org.eclipse.richbeans.examples/src/org/eclipse/richbeans/examples/ExampleFactory.java
- org.eclipse.richbeans.examples/src/org/eclipse/richbeans/examples/IShellCreator.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/Activator.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/file/FileSelectionDialog.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesEventDelegate.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesItemEvent.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/event/SeriesItemListener.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/CComboWithEntryCellEditorData.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/LongStringCellEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/cell/LongStringDialog.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/decorator/IDecoratorValidator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/IShuffleListener.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ImmutableShuffleConfiguration.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleBean.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleConfiguration.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleContentProvider.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleDirection.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleEvent.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/shuffle/ShuffleViewer.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/wrappers/ColorSelectorWrapper.java
https://github.com/eclipse/richbeans/issues/5
> Fix to missing headers

- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
Signed-off-by: Jacob Filik <jacob.filik@diamond.ac.uk>
> Add option to add item before selected item in SeriesTable

- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/scalebox/NumberBox.java
Signed-off-by: Douglas Winter <douglas.winter@diamond.ac.uk>
> Fix inconsistent bounds check in NumberBox

- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/binding/IBeanController.java
- org.eclipse.richbeans.binding/src/org/eclipse/richbeans/binding/BeanController.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/BeanConfigurator.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/BeanWrapper.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/GridListEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/HorizontalListEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/ListEditor.java
- org.eclipse.richbeans.widgets/src/org/eclipse/richbeans/widgets/selector/VerticalListEditor.java
https://github.com/eclipse/richbeans/issues/130
This is accessible through a functional interface.
> Added mechanism to configure a bean as it is added.

- org.eclipse.richbeans.api/src/org/eclipse/richbeans/api/binding/IBeanController.java
- org.eclipse.richbeans.binding/src/org/eclipse/richbeans/binding/BeanController.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesItemView.java
- org.eclipse.richbeans.widgets.file/src/org/eclipse/richbeans/widgets/table/SeriesTable.java
https://github.com/eclipse/richbeans/issues/137
> Issues 137
